apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: greeter
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/eliranKimi/iac-githops-repo.git'
    path: manifests
    targetRevision: initial-setup
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: grpc-proxyless
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
