apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeter-client
  namespace: grpc-proxyless
  labels:
    app: greeter-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greeter-client
  template:
    metadata:
      labels:
        app: greeter-client
    spec:
      serviceAccountName: greeter-service-account
      containers:
      - name: greeter-client
        image: us-central1-docker.pkg.dev/utila-eliran-home/greeter/greeter:latest
        command: ["/client"]
